name: Static Code Security Analysis (psalm)

on:
  push:
    branches: [ master, main, demo ]
  pull_request:
    branches: [ master, main, demo ]

jobs:
  analyze:
    Name: Code Scanning (Psalm)
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions:6.10.3
        with:
          security_analysis: true
          report_file: results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

